version: "3.9"

services:
  db:
    container_name: users-service-db
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: "gspot_users"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - db

  web_users:
    depends_on:
      - db
    networks:
      - db

volumes:
  db:
networks:
  db:
