name: Django CI/CD for games
on:
  push:
    branches: [ "games" ]
  pull_request:
    branches: [ "games" ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Build and run containers
      run: |
        cd backend/games && docker-compose up -d --build
